version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest discover  
      - run: pip install -r requirements.txt
   

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
